---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  label: 
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
    - name: {{ .Chart.Name }}-http
      protocol: TCP
      port: 8080
      targetPort: http-web
